esphome:
  name: first
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_name
  password: !secret wifi_pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret esp_ap
    password: !secret esp_pass

captive_portal:

# Enable logging
logger:

web_server:
  port: 80

# Enable Home Assistant API
api:
  password: !secret esp_api

ota:
  password: !secret esp_api

status_led:
  pin: GPIO16

output:
  - platform: gpio
    pin: 15
    id: gpio15

light:
  - platform: binary
    name: "light_gpio15"
    id: light_gpio15
    output: gpio15

binary_sensor:
  - platform: gpio
    pin: 5
    name: gpio5
    id: gpio5
    on_release:
      then:
      - light.toggle: light_gpio15

sensor:
  - platform: wifi_signal
    name: "vrey_switch_wifi"
    update_interval: 60s